# Generated by Django 5.2.4 on 2025-08-04 16:35

import adminapp.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezingCategory',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('tariff', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlazePercentage',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('party_name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('basic_unit', models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LTR', 'Liter')], default='KG', max_length=20)),
                ('precision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeelingOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingCenter',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('freezing_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingSpot',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingSupervisor',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('capacity_per_day_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('documentation_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logistics_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyers_agent_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('store_type', models.CharField(choices=[('Retail', 'Retail'), ('Warehouse', 'Warehouse')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('freezing_tariff', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('owner', 'Owner')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_peeling', models.BooleanField(default=False)),
                ('peeling_method', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGrade',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.localpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingAgent',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('purchasingSpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingspot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeelingCharge',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeling_for_item', to='adminapp.item')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.shed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingagent')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingspot')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingsupervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPurchaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ice_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading_and_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peeling_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='adminapp.spotpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.spotpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
