# Generated by Django 5.2.4 on 2025-08-31 11:11

import adminapp.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezingCategory',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tariff', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlazePercentage',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('percentage', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('party_name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('basic_unit', models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LTR', 'Liter')], default='KG', max_length=20)),
                ('precision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeelingOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeelingShedSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('spot_purchase_date', models.DateField(blank=True, null=True)),
                ('SpotPurchase_total_boxes', models.PositiveIntegerField()),
                ('SpotPurchase_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpotPurchase_average_box_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boxes_received_shed', models.PositiveIntegerField(default=0)),
                ('quantity_received_shed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingCenter',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('freezing_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingSpot',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=150, unique=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingSupervisor',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('dollar_rate_to_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_rent_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('capacity_per_day_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentOverhead',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('documentation_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logistics_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyers_agent_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('store_type', models.CharField(choices=[('Retail', 'Retail'), ('Warehouse', 'Warehouse')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('freezing_tariff', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_peeling', models.BooleanField(default=False)),
                ('peeling_method', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGrade',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('grade', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('quality', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreezingEntryLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freezing_date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('local_purchase_date', models.DateField(blank=True, null=True)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_slab', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freezing_status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.localpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeelingShedPeelingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeling_types', to='adminapp.peelingshedsupply')),
            ],
        ),
        migrations.CreateModel(
            name='PreShipmentWorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingAgent',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('purchasingSpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingspot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='peelingshedsupply',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.shed'),
        ),
        migrations.CreateModel(
            name='ShedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('item', models.ForeignKey(limit_choices_to={'is_peeling': True}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shed_items', to='adminapp.shed')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreShipmentWorkOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('loss', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('peeling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.preshipmentworkout')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.localpurchase')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemgrade',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.CreateModel(
            name='SpotPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingagent')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingspot')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingsupervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='peelingshedsupply',
            name='spot_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.spotpurchase'),
        ),
        migrations.CreateModel(
            name='FreezingEntrySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freezing_date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('spot_purchase_date', models.DateField(blank=True, null=True)),
                ('total_yield_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_slab', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_c_s', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freezing_status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50)),
                ('spot_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_entries', to='adminapp.purchasingagent')),
                ('spot_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_entries', to='adminapp.purchasingsupervisor')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_entries', to='adminapp.spotpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPurchaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ice_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading_and_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peeling_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='adminapp.spotpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.spotpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='peelingshedsupply',
            name='spot_purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.spotpurchaseitem'),
        ),
        migrations.CreateModel(
            name='FreezingEntrySpotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slab_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_s_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_rate_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_rate_item_to_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('freezing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.freezingentryspot')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_item_entries', to='adminapp.item')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('peeling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
                ('processing_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_shed_items', to='adminapp.shed')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreezingEntryLocalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slab_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('c_s_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('freezing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.freezingentrylocal')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('peeling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
                ('processing_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
