# Generated by Django 5.2.4 on 2025-07-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peelingcharge',
            name='is_peeling',
        ),
    ]
