# Generated by Django 5.2.4 on 2025-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
