# Generated by Django 5.2.4 on 2025-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
