# Generated by Django 5.2.4 on 2025-08-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_shed_code_alter_shed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peelingshedsupply',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='peelingshedsupply',
            name='peeling_type',
        ),
        migrations.CreateModel(
            name='PeelingShedPeelingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeling_types', to='adminapp.peelingshedsupply')),
            ],
        ),
    ]
