# Generated by Django 5.2.4 on 2025-07-30 09:49

import adminapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_spotpurchaseitem_boxes_alter_freezingcategory_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPurchase',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('party_name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPurchaseItem',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.localpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
