# Generated by Django 5.2.4 on 2025-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
