# Generated by Django 5.2.4 on 2025-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_itemtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freezingentryspot',
            old_name='total_yield',
            new_name='total_yield_percentage',
        ),
        migrations.RemoveField(
            model_name='freezingentryspot',
            name='yield_percentage',
        ),
        migrations.AddField(
            model_name='freezingentryspotitem',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
