# Generated by Django 5.2.4 on 2025-08-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_total_yield_freezingentryspot_total_yield_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezingentryspot',
            name='voucher_number',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freezingentryspot',
            name='spot_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_entries', to='adminapp.purchasingagent'),
        ),
        migrations.AlterField(
            model_name='freezingentryspot',
            name='spot_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_entries', to='adminapp.purchasingsupervisor'),
        ),
    ]
