# Generated by Django 5.2.4 on 2025-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_freezingcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glazepercentage',
            name='percentage',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
