# Generated by Django 5.2.4 on 2025-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_localpurchase_localpurchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='species',
        ),
        migrations.AddField(
            model_name='itemgrade',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
