# Generated by Django 5.2.4 on 2025-08-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_freezingentryspot_voucher_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_item_entries', to='adminapp.item'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='peeling_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
    ]
