# Generated by Django 5.2.4 on 2025-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_glazepercentage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembrand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
