# Generated by Django 5.2.4 on 2025-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_freezingentrylocal_total_c_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peelingshedsupply',
            name='SpotPurchase_average_box_weight',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
    ]
