# Generated by Django 5.2.4 on 2025-08-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_freezingentryspotitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentryspot',
            name='freezing_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_shed_items', to='adminapp.shed'),
        ),
    ]
