# Generated by Django 5.2.4 on 2025-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_itembrand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentrylocal',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='freezingentryspot',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='peelingshedsupply',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
