# Generated by Django 5.2.4 on 2025-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_peelingshedsupply_spotpurchase_average_box_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingunit',
            name='factor',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
    ]
