# Generated by Django 5.2.4 on 2025-09-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_packingunit_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='freezing_tariff',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TenantFreezingTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_tariffs', to='adminapp.freezingcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezing_tariffs', to='adminapp.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'category')},
            },
        ),
    ]
