# Generated by Django 5.2.4 on 2025-08-08 11:17

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_freezingentryspot_freezing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(default=adminapp.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('dollar_rate_to_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_rent_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
