# Generated by Django 5.2.4 on 2025-08-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezingentryspot',
            name='processing_center',
        ),
        migrations.RemoveField(
            model_name='freezingentryspot',
            name='store',
        ),
        migrations.AddField(
            model_name='freezingentryspotitem',
            name='processing_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter'),
        ),
        migrations.AddField(
            model_name='freezingentryspotitem',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store'),
        ),
    ]
