# Generated by Django 5.2.4 on 2025-08-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_freezingentryspot_processing_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezingEntryLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freezing_date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50)),
                ('local_purchase_date', models.DateField(blank=True, null=True)),
                ('total_yield_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_slab', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freezing_status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.localpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreezingEntryLocalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slab_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('c_s_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('freezing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.freezingentrylocal')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('peeling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('processing_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
