# Generated by Django 5.2.4 on 2025-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_freezingentrytenant_freezingentrytenantitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezingentrytenant',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
