# Generated by Django 5.2.4 on 2025-09-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_freezingentrytenant_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freezing_date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('total_slab', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('freezing_status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='complete', max_length=50)),
                ('tenant_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleTenantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slab_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('c_s_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('freezing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.saletenant')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('processing_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
