# Generated by Django 5.2.4 on 2025-08-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_freezingentrylocal_freezingentrylocalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreShipmentWorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreShipmentWorkOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_per_kg_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_rate_item_to_inr_get', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('peeling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.preshipmentworkout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
