# Generated by Django 5.2.4 on 2025-09-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_saletenant_saletenantitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleTenant',
            new_name='ReturnTenant',
        ),
        migrations.RenameModel(
            old_name='SaleTenantItem',
            new_name='ReturnTenantItem',
        ),
    ]
