# Generated by Django 5.2.4 on 2025-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_preshipmentworkout_preshipmentworkoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preshipmentworkoutitem',
            name='loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='preshipmentworkoutitem',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
