# Generated by Django 5.2.4 on 2025-09-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_rename_saletenant_returntenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntenantitem',
            name='original_item',
            field=models.ForeignKey(blank=True, help_text='Reference to the original stock lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_items', to='adminapp.freezingentrytenantitem'),
        ),
    ]
