# Generated by Django 5.2.4 on 2025-09-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_returntenantitem_original_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returntenant',
            old_name='freezing_date',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='returntenant',
            old_name='freezing_status',
            new_name='return_status',
        ),
        migrations.RenameField(
            model_name='returntenantitem',
            old_name='freezing_entry',
            new_name='return_entry',
        ),
    ]
