# Generated by Django 5.2.4 on 2025-08-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_freezingcategory_code_alter_itemcategory_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezingentrylocalitem',
            name='yield_percentage',
        ),
    ]
