# Generated by Django 5.2.4 on 2025-09-11 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_rename_freezing_date_returntenant_return_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_slabs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='adminapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantBillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_start_date', models.DateField()),
                ('billing_frequency_days', models.PositiveIntegerField(help_text='Number of days between automatic bill generation')),
                ('last_bill_generated_date', models.DateField(blank=True, null=True)),
                ('next_bill_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='adminapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_stored', models.PositiveIntegerField()),
                ('tariff_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slab_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('c_s_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kg_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.tenantbill')),
                ('freezing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingentrytenant')),
                ('freezing_entry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingentrytenantitem')),
            ],
        ),
    ]
