# Generated by Django 5.2.4 on 2025-08-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_remove_freezingentrylocalitem_yield_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezingentrylocal',
            name='total_yield_percentage',
        ),
    ]
