# Generated by Django 5.2.4 on 2025-09-15 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tenantbill_tenantbillingconfiguration_tenantbillitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('glaze', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('selling_type', models.CharField(blank=True, max_length=50, null=True)),
                ('item_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('cs_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated_from_spot', models.DateTimeField(blank=True, null=True)),
                ('last_updated_from_local', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('source_local_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.freezingentrylocal')),
                ('source_spot_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.freezingentryspot')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
            ],
            options={
                'unique_together': {('store', 'item', 'brand', 'item_quality', 'unit', 'glaze', 'species', 'item_grade', 'source_reference')},
            },
        ),
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='adminapp.store')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='adminapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('plus_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minus_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cs_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.stock')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.storetransfer')),
            ],
            options={
                'unique_together': {('transfer', 'stock', 'item_grade')},
            },
        ),
    ]
