# Generated by Django 5.2.4 on 2025-09-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tenantbill_tenantbillingconfiguration_tenantbillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpurchase',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='spotpurchaseitem',
            name='total_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='peeling_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='shed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezing_shed_items', to='adminapp.shed'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='adminapp.store')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='adminapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
                ('freezing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemgrade')),
                ('item_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.species')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.storetransfer')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.packingunit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kg_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
                ('freezing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemgrade')),
                ('item_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.species')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.packingunit')),
            ],
            options={
                'unique_together': {('store', 'item', 'brand', 'item_quality', 'unit', 'glaze', 'species', 'item_grade')},
            },
        ),
    ]
