# Generated by Django 5.2.4 on 2025-08-26 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_freezingentrylocal_total_yield_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
