# Generated by Django 5.2.4 on 2025-09-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_alter_stock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'item', 'brand', 'item_quality', 'unit', 'glaze', 'species', 'item_grade')},
        ),
        migrations.AlterField(
            model_name='stock',
            name='glaze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.glazepercentage'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemgrade'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.packingunit'),
        ),
        migrations.AlterField(
            model_name='storetransferitem',
            name='glaze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.glazepercentage'),
        ),
        migrations.AlterField(
            model_name='storetransferitem',
            name='item_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemgrade'),
        ),
        migrations.AlterField(
            model_name='storetransferitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='storetransferitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.packingunit'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated_from_local',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated_from_spot',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='selling_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='source_local_entry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='source_spot_entry',
        ),
    ]
