# Generated by Django 5.2.4 on 2025-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_stock_unique_together_alter_stock_glaze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='usd_rate_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='usd_rate_item_to_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='usd_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
