# Generated by Django 5.2.4 on 2025-09-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_stock_usd_rate_item_stock_usd_rate_item_to_inr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
    ]
