# Generated by Django 5.2.4 on 2025-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransfer',
            name='voucher_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
