# Generated by Django 5.2.4 on 2025-09-18 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_storetransfer_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.localpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='PeelingShedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.shed')),
            ],
        ),
        migrations.CreateModel(
            name='SpotAgentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingagent')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchasingsupervisor')),
            ],
        ),
        migrations.CreateModel(
            name='TenantVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tenant')),
            ],
        ),
    ]
