# Generated by Django 5.2.4 on 2025-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_localpurchasevoucher_peelingshedvoucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpurchase',
            name='total_purchase_amount_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
