# Generated by Django 5.2.4 on 2025-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_spotpurchase_total_purchase_amount_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotpurchase',
            name='total_purchase_amount_per_kg',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
        ),
    ]
