# Generated by Django 5.2.4 on 2025-09-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_localparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpurchase',
            name='party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.localparty'),
        ),
    ]
