# Generated by Django 5.2.4 on 2025-09-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_alter_localpurchase_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantvoucher',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantvoucher',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
