# Generated by Django 5.2.4 on 2025-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_tenantvoucher_remain_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peelingshedsupply',
            name='SpotPurchase_balance_boxes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
